### ISSUE TITLE
Motor performance curve has odd blip at the 25% load

### ISSUE THREAD

**Issue by gaccawi** [ORNL-AMO/PSAT#3]
![image](https://cloud.githubusercontent.com/assets/8973004/20903741/8bbf0b6a-bb0a-11e6-8a1f-bfe054edabdd.png)

**Comment by mbadams5** [comment]
I believe ORNL-AMO/AMO-Tools-Suite@06553a4439c1ca4aa9c666c57c4c888253269605 fixes this issue.

When I tested locally it now produces the following graph.
![image](https://cloud.githubusercontent.com/assets/2001544/20903796/c0146ebe-bb0a-11e6-8f00-6cfde185dbdf.png)

I would still like @c0desimple to verify though.

**Comment by c0desimple** [comment]
Verified.  Consider me impressed.  I'm not sure where to even go in the spreadsheets to get the answers you put in the unit tests, let alone fix the issue.  Seems 'weird' to me that lack of '100' constant would cause a problem yet just at that point.  But the graph looks prettier, so closing..

**Comment by mbadams5** [comment]
@c0desimple Basically the equation needs the `loadFactor` in the form 90.1 versus 0.901, hence the multiplication by 100.
